version: '3.5' 

services: 

    exercise_210_frontend: 
      #image: node:14-buster
      build:
        context: ./frontend/
        dockerfile: Dockerfile
      ports: 
        - 5000:5000
      container_name: exercise_210_frontend
      
      
    exercise_210_backend: 
      #image: devopsdockeruh/simple-web-service
      
      build:
        context: ./backend/
        dockerfile: Dockerfile
      environment:
        - REDIS_HOST=exercise_210_redis
        - POSTGRES_HOST=exercise_210_postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=mysecretpassword
        - POSTGRES_DATABASE=postgres
        - REQUEST_ORIGIN=http://localhost
      ports: 
        - 8080:8080
      depends_on:
        - exercise_210_postgres
      container_name: exercise_210_backend
      
    exercise_210_redis: 
      image: redis
      #build: .
      #ports: 
        #- 6379:6379
      container_name: exercise_210_redis
      
    exercise_210_postgres: 
      image: postgres:latest
      #build: .
      environment:
        - POSTGRES_PASSWORD=mysecretpassword
      volumes:
        - ./database:/var/lib/postgresql/data
      #ports: 
        #- 6379:6379
      container_name: exercise_210_postgres
      
    exercise_210_nginx: 
      image: nginx:latest
      #build: .
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      #environment:
        #- POSTGRES_PASSWORD=mysecretpassword
      ports: 
        - 80:80
      depends_on:
        - exercise_210_backend
        - exercise_210_frontend
      container_name: exercise_210_nginx
