version: '3.5' 

services: 

    exercise_203_frontend: 
      #image: node:14-buster
      build:
        context: ./frontend/
        dockerfile: Dockerfile
      ports: 
        - 5000:5000
      container_name: exercise_203_frontend
      
      
    exercise_203_backend: 
      #image: devopsdockeruh/simple-web-service
      
      build:
        context: ./backend/
        dockerfile: Dockerfile
      ports: 
        - 8080:8080
      container_name: exercise_203_backend
