FROM node:14-alpine 
WORKDIR /user/src/myapp
COPY ./example-frontend .
ARG REACT_APP_BACKEND_URL=http://localhost:8080
RUN npm install && \
	npm run build && \
	npm install -g serve 


FROM node:14-alpine 

WORKDIR /user/src/myapp
COPY --from=0 /user/src/myapp/build/ ./build
RUN npm install -g serve 
USER 1000:1000
CMD ["serve", "-s", "-l", "5000", "build"]
EXPOSE 5000
