version: '3.5' 

services: 

    exercise_208_frontend: 
      #image: node:14-buster
      build:
        context: ./frontend/
        dockerfile: Dockerfile
      ports: 
        - 5000:5000
      container_name: exercise_208_frontend
      
      
    exercise_208_backend: 
      #image: devopsdockeruh/simple-web-service
      
      build:
        context: ./backend/
        dockerfile: Dockerfile
      environment:
        - REDIS_HOST=exercise_208_redis
        - POSTGRES_HOST=exercise_208_postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=mysecretpassword
        - POSTGRES_DATABASE=postgres
      ports: 
        - 8080:8080
      depends_on:
        - exercise_208_postgres
      container_name: exercise_208_backend
      
    exercise_208_redis: 
      image: redis
      #build: .
      #ports: 
        #- 6379:6379
      container_name: exercise_208_redis
      
    exercise_208_postgres: 
      image: postgres:latest
      #build: .
      environment:
        - POSTGRES_PASSWORD=mysecretpassword
      #ports: 
        #- 6379:6379
      container_name: exercise_208_postgres
      
    exercise_208_nginx: 
      image: nginx:latest
      #build: .
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      #environment:
        #- POSTGRES_PASSWORD=mysecretpassword
      ports: 
        - 80:80
      depends_on:
        - exercise_208_backend
        - exercise_208_frontend
      container_name: exercise_208_nginx
